[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1a0"
#tag_format = "$major.$minor.$patch$prerelease"
major_version_zero = true
## annotated_tag = true
#update_changelog_on_bump = false
#version_files = [
#    "paasify/version.py:__version__",
#    "pyproject.py:version"
#]
