default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

exclude: "docs/src/.*"



repos:
- hooks:
  - id: check-added-large-files
  # - id: trailing-whitespace
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: check-symlinks
  # - id: check-yaml
  - id: destroyed-symlinks
  - id: detect-private-key
  # - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
#- hooks:
#  - id: markdownlint
#  repo: https://github.com/markdownlint/markdownlint
#  rev: v0.12.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.37.0
    #- hooks:
    #  - id: autopep8
    #  repo: https://github.com/pre-commit/mirrors-autopep8
    #  rev: v2.0.0
- repo: https://github.com/adamchainz/blacken-docs
  rev: "v1.12.1"  # replace with latest tag on GitHub
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black==22.12.0
- hooks:
  - id: flake8
  repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
