name: Install Paasify

on: 
  workflow_call:
    inputs:
      python_versions:
        description: 'Version of python to build ["3.7", "3.8", "3.9"]'
        required: true
        type: string
        default: '["3.9"]'

      poetry_versions:
        description: 'Version of Poetry to use'
        required: true
        type: string
        default: '["1.2.1"]'

    secrets:
      access_token:
        description: 'Github Secret Token to check out the repo'

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      python_versions: ${{ steps.setVariables.outputs.python_versions }}
      poetry_versions: ${{ steps.setVariables.outputs.poetry_versions }}
    steps:
      - id: setVariables
        run: |
          echo "python_versions=$python_versions"
          echo "poetry_versions=$poetry_versions"
          echo "python_versions=$python_versions" >> $GITHUB_OUTPUT
          echo "poetry_versions=$poetry_versions" >> $GITHUB_OUTPUT

        env:
          python_versions: ${{ inputs.python_versions }}
          poetry_versions: ${{ inputs.poetry_versions }}


  install_python:
    runs-on: ubuntu-latest
    needs: setup
    # permissions:
    #   security-events: write
    strategy:
      fail-fast: false
      matrix:
        python_version: ${{fromJson(needs.setup.outputs.python_versions)}}
        poetry_version: ${{fromJson(needs.setup.outputs.poetry_versions)}}
    steps:

    - name: Show infos
      run: |
          echo "python_versions=$python_version"
          echo "poetry_versions=$poetry_version"

    # Prepare devel environment
    # -----------------------------
    
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.access_token }}
        submodules: true

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}


    - name: Load cached poetry
      id: cached-poetry-install
      uses: actions/cache@v3
      with:
        path: .local
        key: poetry-${{ runner.os }}-${{ matrix.python_version }}-${{ matrix.poetry_version }}

    - name: Install Poetry ${{ matrix.poetry_version }} (cached)
      if: steps.cached-poetry-install.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
        installer-parallel: true
        version: ${{ matrix.poetry_version }}


    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ matrix.python_version }}-${{ matrix.poetry_version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies (cached)
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root


  install_paasify:
    runs-on: ubuntu-latest
    needs: install_python
    # permissions:
    #   security-events: write
    strategy:
      fail-fast: false
    steps:

    # Load caches
    # -----------------------------

    - name: Load cached poetry
      id: cached-poetry-install
      uses: actions/cache@v3
      with:
        path: .local
        key: poetry-${{ runner.os }}-${{ matrix.python_version }}-${{ matrix.poetry_version }}

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ matrix.python_version }}-${{ matrix.poetry_version }}-${{ hashFiles('**/poetry.lock') }}

    # Install project
    # -----------------------------
    - name: Install paasify
      run: |
        source .venv/bin/activate
        poetry install --no-interaction

