name: Test Paasify (NEW)

on: 
  workflow_call:
    inputs:
      python_version:
        description: 'Version of python to use'
        required: true
        type: string
        default: "3.9"

      poetry_version:
        description: 'Version of Poetry to use'
        required: true
        type: string
        default: "1.2.1"

    secrets:
      access_token:
        description: 'Github Secret Token to check out the repo'


jobs:

  # Test Paasify
  # =====================================
  test_paasify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:

    # Load caches
    # -----------------------------
    - name: Load cached poetry
      id: cached-poetry-install
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-${{ runner.os }}-${{ inputs.python_version }}-${{ inputs.poetry_version }}

    - name: Load cached project
      id: cached-poetry-project
      uses: actions/cache@v3
      with:
        path: .
        key: prj-${{ runner.os }}-${{ inputs.python_version }}-${{ inputs.poetry_version }}-${{ hashFiles('**') }}

    # Test project
    # -----------------------------
    - name: Test paasify
      run: |
        source .venv/bin/activate
        poetry run pytest --cov

