name: Paasify Beta Builds

on:
  workflow_dispatch:
  push:
    branches:
      - "*-alpha"
      - "*-beta"
      - "*-rc"

jobs:
  python_release_dev:

    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'bump:')"

    strategy:
      fail-fast: false
      # TOFIX:
      # We dont want to use matrix build here for python version
      # We want to use matrix build for wheels on multiple archs
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.2.1"]

    steps:

    - name: Extract release type from branch name
      shell: bash
      run: echo "##[set-output name=release;]$(echo ${GITHUB_REF#*-})"
      id: release


    # Prepare devel environment
    # -----------------------------
    
    - name: "Retrieve source code (${{ steps.release.outputs.release }})"
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        submodules: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.poetry-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install Poetry (cached)
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
        version: ${{ matrix.poetry-version }}
        #installation-arguments: --with=dev --with=doc --with=community

    - name: Install dependencies (cached)
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root

#    # Install project
#    # -----------------------------
#
#    - name: Install paasify
#      run: poetry install --no-interaction
#
#    - name: Run pytest
#      run: poetry run pytest --cov 
#
#
#    # Configure release files and version
#    # -----------------------------
#    - id: cz
#      name: Create bump and changelog
#      uses: commitizen-tools/commitizen-action@master
#      with:
#        github_token: "${{ secrets.ACCESS_TOKEN }}"
#        prerelease: "${{ steps.release.outputs.release }}"
#        changelog: false
#        increment: PATCH
#
#    - name: Print Version
#      run: echo "Bumped to version ${{ steps.cz.outputs.version }}"
#
#
#    # Build package
#    # -----------------------------
#   
#    - name: Build packages
#      run: poetry build --no-interaction
#
#
#    # Create a github release
#    # -----------------------------
#    
#    - uses: "marvinpinto/action-automatic-releases@latest"
#      with:
#        #repo_token: "${{ secrets.GITHUB_TOKEN }}"
#        repo_token: "${{ secrets.ACCESS_TOKEN }}"
#        automatic_release_tag: "latest-${{ steps.release.outputs.release }}"
#        draft: true
#        title: "Development Build"
#        files: |
#          LICENSE.txt
#          CHANGELOG.md
#          dist/*.whl
#          dist/*.tar.gz
#
#
#    # PROD ONLY !!
#    # Prepare secrets
#    #- name: Configure secret key
#    #  run: 
#    #    - name: Add mask
#    #    run: |
#    #      echo "::add-mask::${{ secrets.PYPI_API_TOKEN }}" 
#    #      poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
#
#    ## Publish to pypi
#    #- name: Publish package and wheel on Pypi.org
#    #  run: poetry publish --build --no-interaction
#
