name: Publish stable release (TOFIX)

env:
  python_version: "3.9"
  poetry_version: "1.2.1"

on:
  push:
    tags:
      # This is prod for now, to be changed to dev
      - '[0-9]+.[0-9]+.[0-9]+'

      
jobs:

  install:
    runs-on: ubuntu-latest
    steps:
    
      # Install build env
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Load cached env
        id: cached-env-install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: dev_env-${{ runner.os }}-3.9

      - name: Install virtualenv and poetry (cached)
        if: steps.cached-env-install.outputs.cache-hit != 'true'
        run: |
          set -x
          python -m pip install --upgrade pip virtualenv 
          virtualenv ~/.venv

          source ~/.venv/bin/activate
          pip install --upgrade poetry==1.2.1
          poetry config virtualenvs.path ~/.venv
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.create false
          

      # Install project        
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true

      - name: Load cached venv
        id: cached-project-deps
        uses: actions/cache@v3
        with:
          path: ~/.venv
          key: venv-${{ runner.os }}-3.9-${{ hashFiles('**/poetry.lock') }}
        
      - name: Install project dependencies (cached)
        if: steps.cached-project-deps.outputs.cache-hit != 'true'
        run: |
          source ~/.venv/bin/activate
          poetry install -vv --no-interaction --no-root
      
      - name: Install project
        run: |
          source ~/.venv/bin/activate
          poetry install -vv --no-interaction --only-root


  build:
    needs: install
    runs-on: ubuntu-latest

    steps:

      # Load project        
      - name: Load cached venv
        id: cached-project-deps
        uses: actions/cache@v3
        with:
          path: ~/.venv
          key: venv-${{ runner.os }}-3.9-${{ hashFiles('**/poetry.lock') }}
        
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
          submodules: true

      - name: show env
        run: |
          env | sort


      # Load dist        
      - name: Load cached dist
        id: cached-project-dist
        uses: actions/cache@v3
        with:
          path: dist
          key: dist-${{ runner.os }}-3.9-${{ github.ref_name }}

      - name: Build paasify release
        run: |
          set -x
          source ~/.venv/bin/activate

          PREV_TAG=$(git for-each-ref --sort=creatordate --format '%(refname)' refs/tags | tail -n 2 | head -n 1 | sed 's@.*/@@')

          poetry build -vvv

          ls -ahl
          ls -ahl  dist/

          cz changelog --start-rev "$PREV_TAG" --file-name dist/UPDATES.md



  publish_gh:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
          submodules: true

      # Load dist        
      - name: Load cached venv
        id: cached-project-dist
        uses: actions/cache@v3
        with:
          path: dist
          key: dist-${{ runner.os }}-3.9-${{ github.ref_name }}

      - name: Publish Github Release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.ACCESS_TOKEN }}"
          body_path: "dist/UPDATES.md"
          prerelease: false
          name: "Version: ${{github.ref_name}} (stable)"
          tag_name: "${{github.ref_name}}"
          files: |
            LICENSE.txt
            CHANGELOG.md
            dist/UPDATES.md
            dist/*.whl
            dist/*.tar.gz


