name: Create dev release

on:

  workflow_dispatch:
    inputs:

      prerelease:
        description: 'Prerelease type: alpha, beta, rc or empty for stable'
        default: "alpha"
        type: choice
        options:
          - alpha
          - beta
          - rc

      increment:
        description: 'Increment type: MAJOR, MINOR, PATCH or <empty>'
        default: ""
        type: choice
        options:
          - ""
          - MAJOR
          - MINOR
          - PATCH

      changelog:
        description: 'Generate Changelog'
        type: boolean
        default: true


jobs:

  install:
    uses: ./.github/workflows/_install.yaml
    strategy:
      fail-fast: false
    with:
      python_version: '3.9'
      poetry_version: '1.2.1'
    secrets:
      access_token: "${{ secrets.ACCESS_TOKEN }}"

  # install:
  #   runs-on: ubuntu-latest
  #   steps:
    
  #     # Install build env
  #     - name: Set up Python 3
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.9
      
  #     - name: Load cached env
  #       id: cached-env-install
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.local
  #         key: dev_env-${{ runner.os }}-3.9

  #     - name: Install virtualenv and poetry (cached)
  #       if: steps.cached-env-install.outputs.cache-hit != 'true'
  #       run: |
  #         set -x
  #         python -m pip install --upgrade pip virtualenv 
  #         virtualenv ~/.venv

  #         source ~/.venv/bin/activate
  #         pip install --upgrade poetry==1.2.1
  #         poetry config virtualenvs.path ~/.venv
  #         poetry config virtualenvs.in-project false
  #         poetry config virtualenvs.create false
          

  #     # Install project        
  #     - uses: actions/checkout@v3
  #       with:
  #         token: ${{ secrets.ACCESS_TOKEN }}
  #         submodules: true

  #     - name: Load cached venv
  #       id: cached-project-deps
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.venv
  #         key: venv-${{ runner.os }}-3.9-${{ hashFiles('**/poetry.lock') }}
        
  #     - name: Install project dependencies (cached)
  #       if: steps.cached-project-deps.outputs.cache-hit != 'true'
  #       run: |
  #         source ~/.venv/bin/activate
  #         poetry install -vv --no-interaction --no-root
      
  #     - name: Install project
  #       run: |
  #         source ~/.venv/bin/activate
  #         poetry install -vv --no-interaction --only-root

  release:
    needs: install
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'bump:')"

    steps:

      # Load project        
      - name: Load cached venv
        id: cached-project-deps
        uses: actions/cache@v3
        with:
          path: ~/.venv
          key: venv-${{ runner.os }}-3.9-${{ hashFiles('**/poetry.lock') }}
        
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
          submodules: true

      # Bump dist project
      # -----------------------------

      - id: release
        run: |2
          BRANCH=${GITHUB_REF#refs/heads/}
          prerelease="${{github.event.inputs.prerelease}}"
          case "$BRANCH" in
            *-alpha) prerelease=alpha ;;
            *-beta) prerelease=beta ;;
            *-rc) prerelease=rc ;;
          esac

          if [[ "$prerelease" != "${{github.event.inputs.prerelease}}" ]]; then
            echo "Change pre-release because of branch name: '$BRANCH'"
            echo "  ${{github.event.inputs.prerelease}} -> ${prerelease}"
          fi
          echo "prerelease=${prerelease}" >> "$GITHUB_OUTPUT"

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: ${{github.event.inputs.changelog}}
          prerelease: ${{steps.release.outputs.prerelease}}
          increment: ${{github.event.inputs.increment}}

      - name: Print Version
        run: |
          source ~/.venv/bin/activate
          echo "Bumped to version ${{ steps.cz.outputs.version }}"
          echo "Project version: $(poetry version -s)"
          echo "Paasify version: $(paasify --version)"

